### ISSUE TITLE
Batch upload Stuck

### ISSUE THREAD

**Issue by Elie114** [kartoza/IGRAC-GGIS#610] opened 2023-12-12 10:16 UTC
Dear Irwan, 

I am trying to upload data on the GGMN. Unfortunately, it is stuck. 
I am adding a screenshot of the problem. 

Please let me know

Regards,
Elie
<img width="767" alt="Screenshot 2023-12-12 111310" src="https://github.com/kartoza/IGRAC-GGIS/assets/152389569/ccd4b822-6e98-4bac-bce4-37d86aeb80d7">

**Comment by meomancer** [comment] 2023-12-13 01:58
Hi @Elie114 
The problem is the server was restarted but the form is not resumed.

Solution:
- [ ] Create resume button 
- [ ] Resume all in processing form

Could you reupload it for now? I made it done, so you can reupload

**Comment by Elie114** [comment] 2023-12-13 08:24
Dear Irwan, 
I reuploaded the file. 
Should I not close the browser then or turn off my laptop? How did the server restart? 
Please let me know what to do so the upload is not interrupted because these are big files and doing it again is time-consuming. 
Thank you for your assistance.
Regards,
Elie

**Comment by meomancer** [comment] 2023-12-14 09:06
Hi @Elie114 
This will be fixed in the next release (version 4.3.0)
It will be autoresume when server restarted
And we can also resume manually

![Selection_021](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/489cc2c7-6e3c-4f85-a0a8-e8b6210fe784)

**Comment by meomancer** [comment] 2024-01-29 09:27
Hi @Elie114   
Is the upload working fine? 
Do you still encounter the upload become stuck?

Thank you

**Comment by Elie114** [comment] 2024-01-29 10:01
It is good now

**Closed** 2024-01-29 10:17 UTC
