### ISSUE TITLE
network error - can't save map

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#372] opened 2021-02-09 11:45 UTC
I often have that issue when I try to save map edits. Do you know where it might come from? It is frustrating because I lose all my edits
![image](https://user-images.githubusercontent.com/64771599/107359068-82807600-6ad4-11eb-97fa-51acebfaa009.png)

**Comment by meomancer** [comment] 2021-02-09 12:33
i think Network Error is because at that moment, the geoserver is busy 
you could wait a moment and retry to save it

i can't reproduce it, but will retest it later

**Comment by ArnaudIGRAC** [comment] 2021-02-10 08:21
I tried several times. I also tried save as...

**Comment by meomancer** [comment] 2021-02-11 09:39
Found this error, the fix will be deployed tomorrow

**Comment by meomancer** [comment] 2021-02-12 03:09
this fix is deployed @ArnaudIGRAC @seabilwe to production
please check it

**Comment by seabilwe** [comment] 2021-02-12 08:56
@meomancer I was able to save changes made to the map from my side, maybe @ArnaudIGRAC please also check if ts the same for you as well

**Comment by ArnaudIGRAC** [comment] 2021-02-15 10:22
I have that issue again (https://ggis.un-igrac.org/maps/1249/edit).

**Comment by meomancer** [comment] 2021-02-15 10:34
I'm able to save it @ArnaudIGRAC 
what layer did you add to the map?

**Comment by ArnaudIGRAC** [comment] 2021-02-15 10:54
I tried again and I was able to save it too. I haven't figured out why this error message sometimes pops in.

**Comment by meomancer** [comment] 2021-02-15 11:09
this error is because our server can open the connection for maximum 120s or (2 mins)
The map has a lot of layer, that needs to be saved for every layer, that why it's taking too long

What we need is reduce the number of layer, because we can't just increase the maximum time for open connection, because it will affect server to make other process taking too long time too

**Comment by meomancer** [comment] 2021-02-15 11:18
i think we can close this @ArnaudIGRAC @seabilwe 
we can just create ticket about this if we save a map and this problem happens consistenly

**Comment by ArnaudIGRAC** [comment] 2021-02-15 11:25
Is is thus also related to your internet speed?

**Comment by meomancer** [comment] 2021-02-15 11:31
no @ArnaudIGRAC 
this is related to process in the server
so when the server having heavy process, it will slow

when we save a map, it can takes more than 120s
when it hits 120 seconds, it will says "Network Error"

i will increase it to 240s tomorrow

**Closed** 2021-02-15 11:42 UTC
