### ISSUE TITLE
show full time series

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#433] opened 2021-05-17 13:29 UTC
We have got a sample well from Norway, which was uploaded to the GGIS. It includes groundwater level and temperature data:
https://ggis.un-igrac.org/groundwater/record/29075/

Everything is fine but when we want to visualize the data (through the graphs in the form) we have to click 1000 times in “Load more” because it adds data week by week and the series starts in 2012. 

Were we not supposed to have buttons to show daily, weekly or yearly data? https://github.com/kartoza/IGRAC-GGIS/issues/319

**Comment by dimasciput** [comment] 2021-05-18 12:36
Hi @ArnaudIGRAC , 

> Were we not supposed to have buttons to show daily, weekly or yearly data? #319

The chart will only appear in the mapstore but I think we can also add it to the form.
Would you like to have a different button for aggregate chart? Or should we just replace the groundwater chart with the aggregate chart like in the mapstore?

![image](https://user-images.githubusercontent.com/1979569/118651802-1b2f3c00-b810-11eb-8dea-2c31bd5e187b.png)

**Comment by ArnaudIGRAC** [comment] 2021-05-18 13:53
The buttons in mapstore are fine but only the average is shown. Because of memory issues I think.
Ideally, we would like to 
- show individual data AND the average
- let the user decide if he want to see the entire time series or only a subset (in that latter case he defines the interval "from... until...")
I suggest we discuss it next time we meet, once you have shared the cost estimation for the time series analysis tool

**Comment by meomancer** [comment] 2021-05-24 01:41
hi @ArnaudIGRAC 

the problem is the chart in https://ggis.un-igrac.org/groundwater/record/29075/ is based on the rows on the measurement table. This needs to be individuals because the chart need to be updated based on the measurements that user change or added in the edit.

The chart are same with
https://ggis.un-igrac.org/groundwater/record/29075/edit
https://ggis.un-igrac.org/groundwater/record/29075

The solution maybe:
- show chart on https://ggis.un-igrac.org/groundwater/record/29075 same with on the mapstore
- keep the individuals for : https://ggis.un-igrac.org/groundwater/record/29075/edit

For showing individuals, it will reduce performance if we put it on mapstore. We still need to use "load more" to make performance fast.
When we do
> let the user decide if he want to see the entire time series or only a subset (in that latter case he defines the interval "from... until...")

we still need to show using "load more", because if user use timeframe like a year and it has like thousand data, it will definitelly break the connection.

I think we need to discuss it.

For now i will make 
https://ggis.un-igrac.org/groundwater/record/29075 like the mapstore

**Comment by meomancer** [comment] 2021-05-24 04:16
for peformance, @dimasciput said that we can use
https://www.highcharts.com/demo/line-boost

but it is not free

**Comment by meomancer** [comment] 2021-05-24 08:42
hi @ArnaudIGRAC 
could you check on staging:
 
when we are in read mode : https://staging.igrac.kartoza.com/groundwater/record/698/
it will show graph like mapstore

when we edit : https://staging.igrac.kartoza.com/groundwater/record/698/edit
it shows individuals graph

**Comment by ArnaudIGRAC** [comment] 2021-05-25 07:48
Thank you Irwan, I wouldn't make any change for now, we need to discuss first.

**Comment by meomancer** [comment] 2021-05-25 08:11
> If I understand correctly, the issue is fetching all the data from the database (in case there are thousands of data). But when you show the average in Mapstore, you also need to fetch all the data to calculate the average, isn't it?

yes @ArnaudIGRAC

**Comment by ArnaudIGRAC** [comment] 2021-05-25 08:16
so what was the rationale for showing the average only?

**Comment by dimasciput** [comment] 2021-05-25 08:28
> so what was the rationale for showing the average only?

1. The result of the calculation is smaller in terms of the size, so the frontend won't have to wait a long time to download the data.
2. The library that generate and draw the chart is not very good at handling large data. It will also make the browser really slow as it will use up a lot of memory.

@ArnaudIGRAC @meomancer

**Comment by meomancer** [comment] 2021-07-12 02:08
This will be fixed by https://github.com/kartoza/IGRAC-GGIS/issues/442

**Comment by ArnaudIGRAC** [comment] 2021-08-16 07:56
Dear colleagues, where do we stand on this development?

**Comment by meomancer** [comment] 2021-08-16 09:06
hi @ArnaudIGRAC 
could you check this PR?
https://github.com/kartoza/IGRAC-GGIS/issues/442
that PR is fixing this ticket

**Comment by meomancer** [comment] 2021-08-23 04:26
hi @clau1313 @ArnaudIGRAC
the new chart is already released with version 1.2.0
Please check it on https://ggis.un-igrac.org/

**Closed by meomancer** 2021-08-23 04:26 UTC
