### ISSUE TITLE
Batch Upload

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/IGRAC-GGIS#728] opened 2024-10-09 09:58 UTC
Priority: High

I am uploading data to the GGMN; I can see errors, I want to download the Excel file to check the errors but I can't I. I have an Error '' 404 Error Not Found ''.

**Comment by meomancer** [comment] 2024-10-09 10:09
Hi @Eliegergesgerges cc @clau1313 
Here is your report @Eliegergesgerges 

1. It seems you were using xlsx, although importer handling both, but the report is using ods
Here is the link to your report
https://ggis.un-igrac.org/uploaded/gwml2/upload/00_Estonia_wells.report.ods

2. From the error, it seems you are using old template
Please use the latest template that you can download on the batch upload
Because we added 2 news columns

**Comment by Eliegergesgerges** [comment] 2024-10-09 13:10
Hi irwan, 
I tried with the new template and it is .ods; can you please tell me what is the problem now? 
<img width="1255" alt="Screenshot 2024-10-09 150903" src="https://github.com/user-attachments/assets/356bb330-5501-432e-b3c1-821a3e925f23">

**Comment by meomancer** [comment] 2024-10-10 04:09
Hi @Eliegergesgerges 
The problem is on your file, it has "underscore" on the "General Infromation" sheet name
Not sure why, maybe when you save it?

![from upload](https://github.com/user-attachments/assets/457e3bcb-a951-4d70-94a5-4766d3dac797)

Meanwhile on the template, there is no "underscore"
![from template](https://github.com/user-attachments/assets/08e96069-db55-46c0-aba3-0b972e29dfa3)

**Comment by meomancer** [comment] 2024-10-15 02:49
Hi @Eliegergesgerges 
Could you review this ticket?

**Comment by Eliegergesgerges** [comment] 2024-10-15 13:08
Yes, it worked Thank you. 
when I upload .ods by default it changes the name of the page (adds the underscore). However, when I used .xlsx I was able to change and upload the file. And it worked

**Comment by meomancer** [comment] 2024-10-16 00:46
Could we close this @Eliegergesgerges ?
We can revisit if it happens

**Comment by Eliegergesgerges** [comment] 2024-10-16 06:59
Yes

**Closed** 2024-10-17 05:12 UTC
Labels: Priority: High, Support Portal
