### ISSUE TITLE
Download button returns empty files

### ISSUE THREAD

**Issue by SterckxArnaud** [kartoza/IGRAC-GGIS#556] opened 2023-05-24 07:25 UTC
The download button launches the download of a zip file that is empty. I tried with several layers.
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/11b43768-ade9-4796-ba2b-58bba38a4fc7)

**Comment by meomancer** [comment] 2023-05-29 11:11
Hi @ArnaudIGRAC 
This is bug from geonode itself
Another geonode instance : https://dev-geonode.dev.do.kartoza.co.za/

Should we raise ticket to upstream?

**Comment by ArnaudIGRAC** [comment] 2023-05-30 07:00
Hi Irwan, could you please report this issue to GeoNode developers? Hopefully it will be solved in a later version of the software..

**Comment by timlinux** [comment] 2023-06-11 19:47
@meomancer can you please update us on the status of this? Did you report it upstream?

**Comment by meomancer** [comment] 2023-06-12 00:20
hi @timlinux @ArnaudIGRAC 
I have reported today : https://github.com/GeoNode/geonode/issues/11156

**Comment by ArnaudIGRAC** [comment] 2023-06-29 10:07
Hello Irwan, has this bug been fixed by the GeoNode team?

**Comment by meomancer** [comment] 2023-07-14 09:56
Hi @ArnaudIGRAC and @NyakudyaA 
I have pulled latest code from geonode
Now it does not return empty files, but will show error when we click it. That is because it returns 404 not found, which is the file does not exist.

Example: the file is empty
![Selection_013](https://github.com/kartoza/IGRAC-GGIS/assets/4530905/3dd239c7-2a23-4561-b74c-c7d27ee9f91f)

I think it is new feature that the data is still empty from our side. I tried using new upload, and it is working fine.
Maybe there is command that auto fill this files @NyakudyaA ?

**Comment by ArnaudIGRAC** [comment] 2023-09-05 13:52
I thought that this issue would be resolved in version 4.1.1, but it is still bugging. When you click on the download button you now get 
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/d581d4d9-8d93-43ec-ad92-e694f334c13f)
Download is itself not a problem, layers can be downloaded by clicking on "download". I assume the issue is with that button that doesn't launch the right command.

**Comment by meomancer** [comment] 2023-09-05 14:25
It is not bug @ArnaudIGRAC 
We have some missing data on our database as per my comment : https://github.com/kartoza/IGRAC-GGIS/issues/556#issuecomment-1635614019

That is the new data that we don't have on our database (because the dataset was created on older geonode)

I have asked @NyakudyaA if geonode have command to fill the missing data on database

**Comment by meomancer** [comment] 2023-09-20 08:01
Hi @NyakudyaA 

After i checked, the url on the download button is using "Link" with "Original Dataset" name
Example : https://ggis.un-igrac.org/en-us/admin/base/link/121911/change/
The url is : https://ggis.un-igrac.org/download/2437
Which is using : https://github.com/GeoNode/geonode/blob/master/geonode/proxy/views.py#L271
The function is just using temporary files

Another download function is using:
https://ggis.un-igrac.org/datasets/geonode:go_demography_totpopulationPolygon0/dataset_download
It calls https://ggis.un-igrac.org/geoserver/ows?service=WPS&version=1.0.0&REQUEST=Execute

It post
```
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:dwn="http://geoserver.org/wps/download" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:wfs="http://www.opengis.net/wfs" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" service="WPS" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
    <ows:Identifier>gs:Download</ows:Identifier>
    <wps:DataInputs>
        <wps:Input>
            <ows:Identifier>layerName</ows:Identifier>
            <wps:Data>
                <wps:LiteralData>geonode_data:geonode:go_demography_totpopulationPolygon0</wps:LiteralData>
            </wps:Data>
        </wps:Input>
        <wps:Input>
            <ows:Identifier>outputFormat</ows:Identifier>
            <wps:Data>
                <wps:LiteralData>application/zip</wps:LiteralData>
            </wps:Data>
        </wps:Input>
      <wps:Input>
         <ows:Identifier>cropToROI</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>false</wps:LiteralData>
         </wps:Data>
      </wps:Input>
    </wps:DataInputs>
    <wps:ResponseForm>
        <wps:RawDataOutput mimeType="application/zip">
            <ows:Identifier>result</ows:Identifier>
        </wps:RawDataOutput>
    </wps:ResponseForm>
</wps:Execute>
```

But it is error:
```
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 https://ggis.un-igrac.org/geoserver/schemas/ows/1.1.0/owsAll.xsd">
    <ows:Exception exceptionCode="NoApplicableCode">
        <ows:ExceptionText>Unknown process gs:Download</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>
```

Could you help me check why "Unknown process gs:Download"?
The geoserver is kartoza/sadc_gip:geoserver-3.1.netcfd

If above geoserver is working, i will update geonode to check if files is not exist, will use geoserver request instead.

Thank you

**Comment by meomancer** [comment] 2023-09-20 08:48
Hi @NyakudyaA 
Confirmed on my local : upgrading geoserver fix this issue

**Comment by meomancer** [comment] 2023-12-06 06:32
Hi @SterckxArnaud
This is fixed with current deployment (geoserver:2.23.0-geo-v2023.09.15)
Could you check it?

But it is not working on : https://ggis.un-igrac.org/catalogue/#/?f=dataset&d=2246%3Bdataset

Could you help me check this issue @NyakudyaA ?
The error is NullPointer
https://ggis.un-igrac.org/geoserver/ows?service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=bcf6756d-77a2-452d-acc1-da4699b30930&access_token=6yJLprZxCwmD7lEg3EH1qFKop8MstU

**Comment by SterckxArnaud** [comment] 2023-12-07 12:35
There seems to be an error with that layer, it is no longer available in this viewer: https://ggis.un-igrac.org/view/G3P/
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/de96a7a7-b78c-4452-ad5f-c38c825d6a5e)

**Comment by SterckxArnaud** [comment] 2023-12-18 15:06
Hi Irwan, I remarked that some other layers also stopped being available: see for instance: https://ggis.un-igrac.org/catalogue/#/dataset/841 and https://ggis.un-igrac.org/catalogue/#/dataset/842. Could you please investigate?

**Comment by NyakudyaA** [comment] 2023-12-18 16:01
> Hi Irwan, I remarked that some other layers also stopped being available: see for instance: https://ggis.un-igrac.org/catalogue/#/dataset/841 and https://ggis.un-igrac.org/catalogue/#/dataset/842. Could you please investigate?

The first layer is fixed, the second layer looks like it has been deleted from the database. @meomancer Any idea how that could have happened and we could retrieve from backups ?

**Comment by meomancer** [comment] 2023-12-19 02:31
Hi @NyakudyaA @SterckxArnaud 
I'm not sure what is happening for the data, since i didn't touch database when upgrading.

I think we can restore from staging
https://staging.igrac.kartoza.com/catalogue/#/dataset/842

I will check with you and devops

**Comment by meomancer** [comment] 2023-12-21 04:12
Hi @NyakudyaA 
Could you check this ticket?

- [ ] https://github.com/kartoza/IGRAC-GGIS/issues/556#issuecomment-1842175080

The error dataset is covered in this ticket : https://github.com/kartoza/IGRAC-GGIS/issues/619

**Closed** 2023-12-21 08:20 UTC
Labels: bug, geoserver, geonode 4.x.x
