### ISSUE TITLE
Layer not appearing in GeoNode

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#343] opened 2021-01-27 10:32 UTC
Hi @NyakudyaA, The style of the layer is fine when validated , but the layer is not appearing on GeoNode. This on the production site 

- [x] https://ggis.un-igrac.org/layers/igrac:igrac:gwstress_aquifers_globalgroundwaterstress
- [x] https://ggis.un-igrac.org/layers/unhcr:unhcr_study_area (#350)
**- when going to check on GeoServer, this is the issue I am having**
https://ggis.un-igrac.org/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.layer.LayerPage?4
https://ggis.un-igrac.org/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.layer.LayerPage?9

**Other layers with layer not appearing on GeoNode**
- [x] https://ggis.un-igrac.org/layers/twap_public:twap_public:twap_sids_legal_qlt_lndusereg
https://ggis.un-igrac.org/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.layer.LayerPage?13

- [x] https://ggis.un-igrac.org/layers/localhost:igrac:twap_legalaspects_qlt_lndusereg
https://ggis.un-igrac.org/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.layer.LayerPage?17

- [x] https://ggis.un-igrac.org/layers/twap.gwshare:twap.gwshare:sids_groundwatersystems_basicinformation
https://ggis.un-igrac.org/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.layer.LayerPage?43

- [x] https://ggis.un-igrac.org/layers/localhost:igrac:sids
https://ggis.un-igrac.org/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.resource.ResourceConfigurationPage?48&name=sids&wsName=igrac

**Comment by NyakudyaA** [comment] 2021-02-02 11:02
Do you still need me to look at this @seabilwe

**Comment by seabilwe** [comment] 2021-02-02 11:04
> Do you still need me to look at this @seabilwe

Yes, please @NyakudyaA

**Comment by NyakudyaA** [comment] 2021-02-02 16:52
@meomancer cc @lucernae. The staging DB used postgres10 while the production DB uses postgis13 image. Some of the layers which were not rendering here were caused by improper migration of the DB.

For example, the Postgres 10 image uses `st_force_3d` which is deprecated in postgis 13. It is now called `ST_Force3D`. I am not sure how the DB was migrated but just note this for future references

**Comment by NyakudyaA** [comment] 2021-02-02 19:14
@seabilwe the layer https://staging.igrac.kartoza.com/layers/localhost:igrac:sids is not rendering on both staging and production. I suspect this has to do with the name of the layer which has a `:` in the layer name. I suggest changing this if it doesn't affect any viewers

**Comment by lucernae** [comment] 2021-02-04 13:00
> For example, the Postgres 10 image uses st_force_3d which is deprecated in postgis 13. It is now called ST_Force3D. I am not sure how the DB was migrated but just note this for future references

Noted. @NyakudyaA . I migrate it using pg restore. Do you have any recommended articles that will support this kind of Postgis migrations? I'm not comfortable using GeoNode's postgres 10 image for production, so I opt in using our image.

**Comment by ArnaudIGRAC** [comment] 2021-02-09 11:54
Can you also check this layer ?
https://ggis.un-igrac.org/layers/igrac:igrac:go_gwquantity_presoflargesprings

**Comment by meomancer** [comment] 2021-02-16 09:44
could you check this ticket @seabilwe @NyakudyaA ?

**Comment by NyakudyaA** [comment] 2021-02-18 09:38
This is now fixed

**Comment by ArnaudIGRAC** [comment] 2021-02-21 16:19
> Can you also check this layer ?
> https://ggis.un-igrac.org/layers/igrac:igrac:go_gwquantity_presoflargesprings

this layer is still not displaying in GGIS

**Comment by seabilwe** [comment] 2021-02-22 08:15
> > Can you also check this layer ?
> > https://ggis.un-igrac.org/layers/igrac:igrac:go_gwquantity_presoflargesprings
> 
> this layer is still not displaying in GGIS

Hi @NyakudyaA , I just had a look at this layer on Geoserver and the style is okay, but when previewing the layer this is what I get:
![Screenshot from 2021-02-22 09-55-30](https://user-images.githubusercontent.com/56301949/108680630-c755d500-74f6-11eb-8033-e1564b7dc3d2.png)

**Comment by NyakudyaA** [comment] 2021-02-22 16:36
@seabilwe This is a styling issue. The data type defined in the SLD does not match to the column values in the tables

![distin](https://user-images.githubusercontent.com/2510900/108738937-c8a9f080-753c-11eb-9541-ec96b5bd9ba0.png)

Check the SLD that is being used against the old one
```
<?xml version="1.0" encoding="UTF-8"?><sld:StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:sld="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" version="1.0.0">
  <sld:NamedLayer>
    <sld:Name>Default Styler</sld:Name>
    <sld:UserStyle>
      <sld:Name>Default Styler</sld:Name>
      <sld:Title>GO Groundwater quantity Presence of large springs</sld:Title>
      <sld:FeatureTypeStyle>
        <sld:Name>name</sld:Name>
        <sld:Rule>
          <sld:Name>none</sld:Name>
          <sld:Title>none yield &gt; m³/s</sld:Title>
          <ogc:Filter>
            <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>presoflargesprings</ogc:PropertyName>
              <ogc:Literal>none</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
          <sld:PolygonSymbolizer>
            <sld:Fill>
              <sld:CssParameter name="fill">#CEDEF4</sld:CssParameter>
              <sld:CssParameter name="fill-opacity">0.9</sld:CssParameter>
            </sld:Fill>
            <sld:Stroke>
              <sld:CssParameter name="stroke-width">0.5</sld:CssParameter>
            </sld:Stroke>
          </sld:PolygonSymbolizer>
        </sld:Rule>
        <sld:Rule>
          <sld:Name>few</sld:Name>
          <sld:Title>few yield &gt; m³/s</sld:Title>
          <ogc:Filter>
            <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>presoflargesprings</ogc:PropertyName>
              <ogc:Literal>few</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
          <sld:PolygonSymbolizer>
            <sld:Fill>
              <sld:CssParameter name="fill">#A9C5EB</sld:CssParameter>
              <sld:CssParameter name="fill-opacity">0.9</sld:CssParameter>
            </sld:Fill>
            <sld:Stroke>
              <sld:CssParameter name="stroke-width">0.5</sld:CssParameter>
            </sld:Stroke>
          </sld:PolygonSymbolizer>
        </sld:Rule>
        <sld:Rule>
          <sld:Name>many</sld:Name>
          <sld:Title>many yield &gt; m³/s</sld:Title>
          <ogc:Filter>
            <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>presoflargesprings</ogc:PropertyName>
              <ogc:Literal>many</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
          <sld:PolygonSymbolizer>
            <sld:Fill>
              <sld:CssParameter name="fill">#7BA7E1</sld:CssParameter>
              <sld:CssParameter name="fill-opacity">0.9</sld:CssParameter>
            </sld:Fill>
            <sld:Stroke>
              <sld:CssParameter name="stroke-width">0.5</sld:CssParameter>
            </sld:Stroke>
          </sld:PolygonSymbolizer>
        </sld:Rule>
        <sld:Rule>
          <sld:Name>null</sld:Name>
          <sld:Title>No information available</sld:Title>
          <ogc:Filter>
            <ogc:Or>
              <ogc:PropertyIsNull>
                <ogc:PropertyName>presoflargesprings</ogc:PropertyName>
              </ogc:PropertyIsNull>
              <ogc:PropertyIsEqualTo>
                <ogc:PropertyName>presoflargesprings</ogc:PropertyName>
                <ogc:Literal>-9999</ogc:Literal>
              </ogc:PropertyIsEqualTo>
            </ogc:Or>
          </ogc:Filter>
          <sld:PolygonSymbolizer>
            <sld:Fill>
              <sld:CssParameter name="fill">#FFFFFF</sld:CssParameter>
              <sld:CssParameter name="fill-opacity">0.9</sld:CssParameter>
            </sld:Fill>
            <sld:Stroke>
              <sld:CssParameter name="stroke-width">0.5</sld:CssParameter>
            </sld:Stroke>
          </sld:PolygonSymbolizer>
        </sld:Rule>
      </sld:FeatureTypeStyle>
    </sld:UserStyle>
  </sld:NamedLayer>
</sld:StyledLayerDescriptor>

```

**Closed** 2021-02-24 10:03 UTC
